artifacts_folder: artifacts

downloading_data:
  source_dir: artifacts/raw_data
  source_URL: karakaggle/kaggle-cat-vs-dog-dataset

preproccessed_data:
  unzip_dir: artifacts/unzip_dir
  datasets_dir: artifacts/datasets
  train_dir: artifacts/datasets/train
  test_dir: artifacts/datasets/testn 